service: gcp-function-template

provider:
  name: google
  runtime: nodejs10
  project: ${file(../../stages/${opt:stage}.yml):PROJECT}
  region: ${file(../../stages/${opt:stage}.yml):REGION}
  # the path to the credentials file needs to be absolute
  credentials: ${file(../../stages/${opt:stage}.yml):KEYFILE_PATH}
  labels:
    application: ${file(../../stages/${opt:stage}.yml):LABEL_APP}
  environment:
    PROJECT: ${file(../../stages/${opt:stage}.yml):PROJECT}
    REGION: ${file(../../stages/${opt:stage}.yml):REGION}

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-google-cloudfunctions

package:
  exclude:
    - node_modules/**
    - .gitignore
    - .git/**

functions:
  hello:
    handler: hello
    events:
      - http: hello
